$scope.countries = [ 
    {name: 'Afghanistan', code: 'AF'},
    {name: 'Åland Islands', code: 'AX'},
    {name: 'Albania', code: 'AL'},
    {name: 'Algeria', code: 'DZ'},
    {name: 'American Samoa', code: 'AS'},
    {name: 'Andorra', code: 'AD'},
    {name: 'Angola', code: 'AO'},
    {name: 'Anguilla', code: 'AI'},
    {name: 'Antarctica', code: 'AQ'},
    {name: 'Antigua and Barbuda', code: 'AG'},
    {name: 'Argentina', code: 'AR'},
    {name: 'Armenia', code: 'AM'},
    {name: 'Aruba', code: 'AW'},
    {name: 'Australia', code: 'AU'},
    {name: 'Austria', code: 'AT'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'country', code: 'code'},
    {name: 'Zimbabwe', code: 'ZW'}
];